spring:
  cloud:
    gateway:
      routes:
      - id: fallback_service
        uri: https://cn-gateway-service.apps.pcfone.io
        predicates:
          - Path=/cf/v1/weather/**,/cf/v1/cities/**
        filters:
          - StripPrefix=1        
