service:
  city: cn-city-service
  weather: cn-weather-service
  protocol: http
  fallback: cn-egateway-service
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        # locator:
        #   enabled: true
        #   url-expression: "'http://'+serviceId"
        #   lower-case-service-id: true
      enabled: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true

