service:
  city: http://cn-city-service
  weather: http://cn-weather-service
  fallback: https://cn-gateway-service.apps.pcfone.io
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
          lower-case-service-id: true
      enabled: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true

