service:
  protocol: http
spring:
  cloud:
    gateway:
      routes:
      - id: city_service
        uri: http://cn-city-service
        predicates:
          - Path=/v1/cities/**
      - id: weather_service
        uri: http://cn-weather-service
        predicates:
          - Path=/v1/weather/**
    cloudfoundry:
      # url: 
      # username: 
      # password: 
      # org: 
      # space: 
      discovery:
        use-dns: true
        default-server-port: 8080
        use-container-ip: true
        enabled: true
        internal-domain: apps.internal
