spring:
  cloud:
    gateway:
      routes:
      - id: city_service
        uri: cn-city-service
        predicates:
          - Path=/v1/cities/**
      - id: weather_service
        uri: cn-weather-service
        predicates:
          - Path=/v1/weather/**